[package]
name = "store"
version = "0.0.0"
authors = ["Alex Feinberg <alex@strlen.net>"]
edition = "2021"

[dependencies]
bytes = "1"
futures = "0.3"
anyhow = "1.0"
itertools = "0.10.2"
tokio = { version = "1", features = ["full"] }
derive_more = "0.99.17"

[dev-dependencies]
env_logger = "0.9"
